### ISSUE TITLE
Add support for CookieHub v2

### ISSUE THREAD

**Issue by vzahradnik** [VirtualFox0/gatsby-plugin-cookiehub-banner#1]
CookieHub has now two APIs - stable and new v2, which is in beta at the moment (+90 days premium for free). When I compared the integration notes for both APIs, they integrate very similarly. Therefore, I think it makes sense to add support into this plugin instead of creating a new one (very similar).

Stable API:
https://support.cookiehub.com/hc/en-us/categories/360000950232-CookieHub-v1-current-

New API:
https://support.cookiehub.com/hc/en-us/categories/360002411991-CookieHub-v2

Differences:
- Script source url is different. Instead of `https://cookiehub.net/cc/cookiehubId` it's `https://cookiehub.net/c2/cookiehubId`
- Instead of `window.cookieconsent.initialise(options)`, you use `window.cookiehub.load(options)`
- Events seems to be the same in both APIs

I will look into this, and if I manage to implement this change, I will prepare a pull request.

**Comment by VirtualFox0** [comment]
PR is merged and plugin is published with version 0.1.0.
